# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.cache/wt} [current_project]
set_property parent.project_path {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib briscola [current_project]
set_property target_language VHDL [current_project]
read_ip -quiet {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property is_locked true [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top blk_mem_gen_0 -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all blk_mem_gen_0_

write_checkpoint -force -noxdef blk_mem_gen_0.dcp

catch { report_utilization -file blk_mem_gen_0_utilization_synth.rpt -pb blk_mem_gen_0_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

add_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_stub.v}} -of_objects [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

add_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_stub.vhdl}} -of_objects [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

add_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_sim_netlist.v}} -of_objects [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

add_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_sim_netlist.vhdl}} -of_objects [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

add_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp}} -of_objects [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

if {[file isdir {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.ip_user_files/ip/blk_mem_gen_0}]} {
  catch { 
    file copy -force {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_sim_netlist.v}} {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.ip_user_files/ip/blk_mem_gen_0}
  }
}

if {[file isdir {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.ip_user_files/ip/blk_mem_gen_0}]} {
  catch { 
    file copy -force {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_sim_netlist.vhdl}} {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.ip_user_files/ip/blk_mem_gen_0}
  }
}

if {[file isdir {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.ip_user_files/ip/blk_mem_gen_0}]} {
  catch { 
    file copy -force {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_stub.v}} {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.ip_user_files/ip/blk_mem_gen_0}
  }
}

if {[file isdir {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.ip_user_files/ip/blk_mem_gen_0}]} {
  catch { 
    file copy -force {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0_stub.vhdl}} {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.ip_user_files/ip/blk_mem_gen_0}
  }
}
