# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
# IP: The module: 'clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
# IP: The module: 'clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
