# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.cache/wt} [current_project]
set_property parent.project_path {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib briscola [current_project]
set_property target_language VHDL [current_project]
add_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/images.coe}}
add_files -quiet {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}]
add_files -quiet {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.dcp}}]
read_vhdl -vhdl2008 -library briscola {
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/new/data.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/AI/Loader.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/AI/Card_Memory.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/new/PRNG.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/AI/Card_Chooser.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/AI/Manager.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/new/Player.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/new/Server.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/AI/AI_block.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/new/Briscola.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/sources_1/new/vga_640x480.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/sources_1/imports/new/vga_top.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/sources_1/new/vga_drawer.vhd}
  {C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/sources_1/imports/Desktop/sound.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/constrs_1/imports/constraints_xdc_vivado/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/colucci/Google Drive/Uni/Second Year - 2015_2016/Second Semester/Computer Architecture/Assignment/2016/Project_personal/briscola/briscola.srcs/constrs_1/imports/constraints_xdc_vivado/Nexys4_Master.xdc}}]


synth_design -top Briscola -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Briscola.dcp

catch { report_utilization -file Briscola_utilization_synth.rpt -pb Briscola_utilization_synth.pb }
